### ISSUE TITLE
Sharing iP code quality feedback [for @wesleybldc]

### ISSUE THREAD

**Issue by soc-se-bot-red** [WesleyBLDC/ip#7]
@wesleybldc We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

Example from [`src/main/java/Willy/task/Task.java` lines `8-8`](https://github.com/wesleybldc/ip/blob/bddf13696a2f162fa761a97fad867fd8a81be13f/src/main/java/Willy/task/Task.java#L8..L8):

```java

    private Boolean status;

``` 

**Suggestion:** Follow the given naming convention for boolean variables/methods (e.g., use a boolean-sounding prefix).You may ignore the above if you think the name already follows the convention (the script can report false positives in some cases)

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

Example from [`src/main/java/Willy/Willy.java` lines `1-1`](https://github.com/wesleybldc/ip/blob/bddf13696a2f162fa761a97fad867fd8a81be13f/src/main/java/Willy/Willy.java#L1..L1):

```java

package Willy;

```

Example from [`src/main/java/Willy/exception/WillyException.java` lines `1-1`](https://github.com/wesleybldc/ip/blob/bddf13696a2f162fa761a97fad867fd8a81be13f/src/main/java/Willy/exception/WillyException.java#L1..L1):

```java

package Willy.exception;

```

Example from [`src/main/java/Willy/parser/Parser.java` lines `1-1`](https://github.com/wesleybldc/ip/blob/bddf13696a2f162fa761a97fad867fd8a81be13f/src/main/java/Willy/parser/Parser.java#L1..L1):

```java

package Willy.parser;

``` 

**Suggestion:** Follow the package naming convention specified by the coding standard.

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

Example from [`src/main/java/Willy/task/TaskList.java` lines `91-91`](https://github.com/wesleybldc/ip/blob/bddf13696a2f162fa761a97fad867fd8a81be13f/src/main/java/Willy/task/TaskList.java#L91..L91):

```java

        // this.getTaskCount());

``` 

**Suggestion:** Remove dead code from the codebase.

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/Willy/Willy.java` lines `30-34`](https://github.com/wesleybldc/ip/blob/bddf13696a2f162fa761a97fad867fd8a81be13f/src/main/java/Willy/Willy.java#L30..L34):

```java

    /**
     * Run command to init parser and scan for next command
     * @throws IOException
     * @throws WillyException
     */

```

Example from [`src/main/java/Willy/Willy.java` lines `47-52`](https://github.com/wesleybldc/ip/blob/bddf13696a2f162fa761a97fad867fd8a81be13f/src/main/java/Willy/Willy.java#L47..L52):

```java

    /**
     * Main function loop to start the application
     * @param args
     * @throws IOException
     * @throws WillyException
     */

```

Example from [`src/main/java/Willy/exception/WillyException.java` lines `7-10`](https://github.com/wesleybldc/ip/blob/bddf13696a2f162fa761a97fad867fd8a81be13f/src/main/java/Willy/exception/WillyException.java#L7..L10):

```java

    /**
     * WillyException that throws a message
     * @param message
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

possible problems in commit [`b519322`](https://github.com/wesleybldc/ip/commit/b5193220c1677974f12accf8a569738cc2085845):

`added javadocs for all class/methods in main`

* Not in imperative mood (?)
             

**Suggestion:** Follow the given [conventions for Git commit messages](https://se-education.org/guides/conventions/git.html) for _future_ commits (no need to modify past commit messages).

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by WesleyBLDC** [comment]
resolved all comments
